"""create shops table

Revision ID: 047ecf18e644
Revises: 
Create Date: 2025-06-22 05:46:56.807524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047ecf18e644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('recommended_reason', sa.Text(), nullable=False),
    sa.Column('congestion_status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shops')
    # ### end Alembic commands ###
