"""Add translation fields to Recipe model

Revision ID: 98d8d32fdb96
Revises: 4b2f9e931c33
Create Date: 2025-08-10 10:50:56.255658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d8d32fdb96'
down_revision = '4b2f9e931c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ingredients_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('instructions_en', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('instructions_en')
        batch_op.drop_column('ingredients_en')
        batch_op.drop_column('title_en')

    # ### end Alembic commands ###
